version: "3.8"

services:
  db:
    container_name: app-db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: app
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db-manager:
    container_name: app-db-manager
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    depends_on: 
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/certs/server.cert
      - pgadmin-data:/certs/server.key
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data: