# Generated by Django 3.1.3 on 2020-11-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_cli', models.CharField(max_length=255, unique=True, verbose_name='CPF cliente')),
                ('f_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('l_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('qty_ser', models.IntegerField(verbose_name='Quantidade de serviços Solicitados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('matr', models.AutoField(primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('cpf_ee', models.CharField(max_length=11, unique=True, verbose_name='CPF funcionário')),
                ('f_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('l_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Telefone')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo')),
                ('salary', models.FloatField(verbose_name='Salário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ACESSÓRIOS', 'Acessórios'), ('CALÇADOS', 'Calçados'), ('ROUPAS', 'Roupas'), ('CAMA', 'Cama'), ('MESA', 'Mesa'), ('BANHO', 'Banho'), ('DIVERSOS', 'Diversos')], max_length=10, verbose_name='Categoria')),
                ('piece', models.CharField(max_length=255, verbose_name='Peça')),
                ('color', models.CharField(choices=[('ESCURO', 'Escuro'), ('CLARO', 'Claro')], max_length=6, verbose_name='Cor')),
                ('qty_piece', models.IntegerField(verbose_name='Quantidade de peças')),
                ('u_value', models.FloatField(verbose_name='Valor unitário')),
                ('obs', models.CharField(max_length=255, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, verbose_name='Tipo de serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('num_so', models.AutoField(primary_key=True, serialize=False)),
                ('exe_date', models.DateTimeField()),
                ('total_value', models.FloatField()),
                ('id_cli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.client')),
                ('id_ser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.service')),
                ('matr_ee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.item')),
                ('id_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.service')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.client')),
                ('id_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.service')),
            ],
        ),
    ]
